name: Update README

on:
  # schedule:
  #   - cron: "45 1,10 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          git diff
          git config --global user.email 734962820@qq.com
          git config --global user.name yujianke100
          cd ..
          git clone https://github.com/yujianke100/yujianke100.git
          cd ./yujianke100.github.io
          sed -i '1s/^/---\npermalink: \/\ntitle: ""\nexcerpt: ""\nauthor_profile: true\nredirect_from:\n  - \/about\/\n  - \/about.html\n---\n/' ../yujianke100/README.md
          mv ../yujianke100/README.md ./_pages/about.md
          git add ./_pages/about.md

          # Check if working tree is clean
          if [[ -z $(git status --porcelain) ]]; then
            echo "Working tree is clean. No changes to commit."
            exit 0
          fi

          git commit -m "Github Action Auto Updated"
          git push
