# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: auto_update

on:
  schedule:
    # run automatically every 12 hours
#     - cron: "0 9 */2 * *"
    - cron: "30 1,10 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # run on every push on the master branch
#   push:
#     branches:
#     - main
  repository_dispatch:
    types: [update_profile]
    
# The sequence of runs in this workflow:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
#       # update recent blog
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Pull in dev.to posts
#         uses: gautamkrishnar/blog-post-workflow@v1
#         with:
#           max_post_count: "5" # 获取几条链接
#           feed_list: "https://blog.csdn.net/u013589741/rss/list"
      - uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        
      - name: 'Working'
        run: |
          pip3 install feedparser 
          python3 main.py
        
      - name: Commit and push if changed
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git diff
          git config --global user.email 734962820@qq.com
          git config --global user.name yujianke100
          git add README.md
          git commit -m "Github Action Auto Updated"
          git push
          
          echo "start"
          git config --global user.email 734962820@qq.com
          git config --global user.name yujianke100
          git clone https://github.com/yujianke100/yujianke100.github.io.git
          echo "clone finished"
          ls
          cp README.md ./yujianke100.github.io/_pages/about.md
          echo "cp finished"
          sed -i '1s/^/---\npermalink: \/\ntitle: ""\nexcerpt: ""\nauthor_profile: true\nredirect_from:\n  - \/about\/\n  - \/about.html\n---\n/' ./yujianke100.github.io/_pages/about.md
          echo "change finished"
          cd ./yujianke100.github.io
          pwd
          git diff
          git config --global user.email 734962820@qq.com
          git config --global user.name yujianke100
          git add ./_pages/about.md
          git commit -m "Github Action Auto Updated"
          git push https://github.com/yujianke100/yujianke100.github.io.git
          
          
